from domain.project.core.selection.selection_strategy import SelectionStrategy
from domain.project.core.selection.multiple_selection_strategy import MultipleSelectionStrategy
from domain.project.core.selection.single_selection_strategy import SingleSelectionStrategy
