@startuml

entity Answer {
  +value: string
  +text: string
}

entity Question {
  +id: QuestionId
  +text: string
  +type: QuestionType
  +availableAnswers: Answer[]
  +selectedAnswers: Answer[]
  +selectAnswers(answers: Answer[]): void
  +deselectAnswers(answers: Answer[]): void
  +actionNeeded: Action
}

entity QuestionId {
  +code: string
}

entity AnswerFactory {
  +createAnswer(value, text): Answer
}

entity QuestionFactory {
  +createQuestion(text, questionType, availableAnswers, selectedAnswers, actionNeeded)
  +createBooleanQuestion(id, text): Question
}

enum Action {
  METRICS_CHECK
}

enum QuestionType {
  BOOLEAN
  SINGLE_CHOICE
  MULTIPLE_CHOICE
  RATING
}

AnswerFactory --> Answer : creates
QuestionFactory --> Question : creates
Question o-right- Answer
Question *-- QuestionId
Question *-- QuestionType
Question *-- "0..1" Action

note left of Question : entity
note right of Answer : value object


@enduml